name: fix_emotion
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  postgres: ^3.2.1
  flutter_native_splash: ^2.2.19
  path: ^1.8.2
  path_provider: ^2.1.0 
  google_nav_bar: ^5.0.6
  fl_chart: ^0.68.0
  supabase_flutter: ^2.5.11
  bcrypt: ^1.1.3
  fluttertoast: ^8.2.6
  tflite_v2: ^1.0.0
  camera: ^0.11.0+1
  shared_preferences: ^2.2.3
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.2.1
  flutter_emoji: ^2.5.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  uuid: ^4.4.2
  provider: ^6.1.2
  google_mlkit_pose_detection: ^0.12.0
  logging: ^1.2.0
  package_info_plus: ^8.0.2
  pdf: ^3.8.1
  printing: ^5.9.0
  mailer: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets\auth.env
    - assets\models\eMotion_tflite_model.tflite
    - assets\images\logo2.png
    - assets\images\Vector01.png
    - assets\images\Vector6.png
    - assets\images\logo.png
    - assets\images\iconDashboard.png
    - assets\images\House_01.png
    - assets\images\Notebook.png
    - assets\images\Settings_Future.png
    - assets\images\aboutUs.png
    - assets\images\emoDict.png
    - assets\images\emoTrack.png
    - assets\models\model.tflite
    - assets\models\labels.txt
    - assets\models\posenet_model.tflite
    - assets\images\faq.png
    - assets\models\ResNet_model_quantized.tflite
    - assets\splashscreen\Sequence_01.gif