name: fix_emotion
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.2
  camera: ^0.10.5+3
  path: ^1.8.2
  path_provider: ^2.1.0
  permission_handler: ^10.2.0
  mime: ^1.0.6
  logging: ^1.2.0
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.6.0

  google_mlkit_commons:
#    path: ../google_mlkit_commons

  google_mlkit_pose_detection:
    path: E:\Repository\fix-emotion\lib\pose-detection\painters\google_mlkit_pose_detection

  fl_chart: ^0.68.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  bcrypt: ^1.1.3
  intl: ^0.19.0
  mailer: ^6.1.2
  google_nav_bar: ^5.0.6
  pdf: ^3.11.1
  printing: ^5.13.2
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.2.1
  tflite_v2: ^1.0.0
  uuid: ^4.5.0
  image: ^4.2.0
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/ml/
    - assets/models/eMotion2.tflite
    - assets/images/
    - assets/auth.env
    - assets/models/eMotion_tflite_model.tflite
    - assets/images/logo2.png
    - assets/images/Vector01.png
    - assets/images/Vector6.png
    - assets/images/logo.png
    - assets/images/iconDashboard.png
    - assets/images/House_01.png
    - assets/images/Notebook.png
    - assets/images/Settings_Future.png
    - assets/images/aboutUs.png
    - assets/images/emoDict.png
    - assets/images/emoTrack.png
    - assets/models/model.tflite
    - assets/models/labels.txt
    - assets/models/posenet_model.tflite
    - assets/images/faq.png
    - assets/models/ResNet_model_quantized.tflite
    - assets/splashscreen/Sequence_01.gif